export const typeOptions = [
  { title: "Film", value: "Film" },
  { title: "Short Film", value: "Short Film" },
  { title: "Documentary", value: "Documentary" },
  { title: "TV Series", value: "TV Series" },
  { title: "Web Series", value: "Web Series" },
];

export const statusOptions = [
  { title: "Public", value: "public" },
  { title: "Private", value: "private" },
];

export const languageOptions = [
  { title: "Afrikaans", value: "Afrikaans" },
  { title: "Albanian", value: "Albanian" },
  { title: "Amharic", value: "Amharic" },
  { title: "Arabic", value: "Arabic" },
  { title: "Armenian", value: "Armenian" },
  { title: "Azerbaijani", value: "Azerbaijani" },
  { title: "Basque", value: "Basque" },
  { title: "Belarusian", value: "Belarusian" },
  { title: "Bosnian", value: "Bosnian" },
  { title: "Bulgarian", value: "Bulgarian" },
  { title: "Catalan", value: "Catalan" },
  { title: "Cebuano", value: "Cebuano" },
  { title: "Chichewa", value: "Chichewa" },
  { title: "Corsican", value: "Corsican" },
  { title: "Croatian", value: "Croatian" },
  { title: "Czech", value: "Czech" },
  { title: "Danish", value: "Danish" },
  { title: "Dutch", value: "Dutch" },
  { title: "English", value: "English" },
  { title: "Esperanto", value: "Esperanto" },
  { title: "Estonian", value: "Estonian" },
  { title: "Finnish", value: "Finnish" },
  { title: "Galician", value: "Galician" },
  { title: "Georgian", value: "Georgian" },
  { title: "Greek", value: "Greek" },
  { title: "Gujarati", value: "Gujarati" },
  { title: "Haitian Creole", value: "Haitian Creole" },
  { title: "Hausa", value: "Hausa" },
  { title: "Hawaiian", value: "Hawaiian" },
  { title: "Hebrew", value: "Hebrew" },
  { title: "Hindi", value: "Hindi" },
  { title: "Hmong", value: "Hmong" },
  { title: "Hungarian", value: "Hungarian" },
  { title: "Icelandic", value: "Icelandic" },
  { title: "Igbo", value: "Igbo" },
  { title: "Indonesian", value: "Indonesian" },
  { title: "Irish", value: "Irish" },
  { title: "Italian", value: "Italian" },
  { title: "Japanese", value: "Japanese" },
  { title: "Javanese", value: "Javanese" },
  { title: "Kannada", value: "Kannada" },
  { title: "Kazakh", value: "Kazakh" },
  { title: "Khmer", value: "Khmer" },
  { title: "Kinyarwanda", value: "Kinyarwanda" },
  { title: "Korean", value: "Korean" },
  { title: "Kurdish", value: "Kurdish" },
  { title: "Kyrgyz", value: "Kyrgyz" },
  { title: "Lao", value: "Lao" },
  { title: "Latin", value: "Latin" },
  { title: "Latvian", value: "Latvian" },
  { title: "Lithuanian", value: "Lithuanian" },
  { title: "Luxembourgian", value: "Luxembourgian" },
  { title: "Macedonian", value: "Macedonian" },
  { title: "Malagasy", value: "Malagasy" },
  { title: "Malay", value: "Malay" },
  { title: "Malayalam", value: "Malayalam" },
  { title: "Maltese", value: "Maltese" },
  { title: "Maori", value: "Maori" },
  { title: "Marathi", value: "Marathi" },
  { title: "Mongolian", value: "Mongolian" },
  { title: "Myanmar", value: "Myanmar" },
  { title: "Nepali", value: "Nepali" },
  { title: "Norwegian", value: "Norwegian" },
  { title: "Nyanja", value: "Nyanja" },
  { title: "Pashto", value: "Pashto" },
  { title: "Persian", value: "Persian" },
  { title: "Polish", value: "Polish" },
  { title: "Portuguese", value: "Portuguese" },
  { title: "Punjabi", value: "Punjabi" },
  { title: "Romanian", value: "Romanian" },
  { title: "Russian", value: "Russian" },
  { title: "Samoan", value: "Samoan" },
  { title: "Scots Gaelic", value: "Scots Gaelic" },
  { title: "Serbian", value: "Serbian" },
  { title: "Sesotho", value: "Sesotho" },
  { title: "Shona", value: "Shona" },
  { title: "Sindhi", value: "Sindhi" },
  { title: "Sinhala", value: "Sinhala" },
  { title: "Slovak", value: "Slovak" },
  { title: "Slovenian", value: "Slovenian" },
  { title: "Somali", value: "Somali" },
  { title: "Spanish", value: "Spanish" },
  { title: "Sundanese", value: "Sundanese" },
  { title: "Swahili", value: "Swahili" },
  { title: "Swedish", value: "Swedish" },
  { title: "Tagalog", value: "Tagalog" },
  { title: "Tajik", value: "Tajik" },
  { title: "Tamil", value: "Tamil" },
  { title: "Telugu", value: "Telugu" },
  { title: "Thai", value: "Thai" },
  { title: "Turkish", value: "Turkish" },
  { title: "Ukrainian", value: "Ukrainian" },
  { title: "Urdu", value: "Urdu" },
  { title: "Uzbek", value: "Uzbek" },
  { title: "Vietnamese", value: "Vietnamese" },
  { title: "Welsh", value: "Welsh" },
  { title: "Xhosa", value: "Xhosa" },
  { title: "Yiddish", value: "Yiddish" },
  { title: "Yoruba", value: "Yoruba" },
  { title: "Zulu", value: "Zulu" },
];

export const nationalityOptions = [
  { title: "Afghan", value: "Afghan" },
  { title: "Albanian", value: "Albanian" },
  { title: "Algerian", value: "Algerian" },
  { title: "American", value: "American" },
  { title: "Andorran", value: "Andorran" },
  { title: "Angolan", value: "Angolan" },
  { title: "Antiguans", value: "Antiguans" },
  { title: "Argentinean", value: "Argentinean" },
  { title: "Armenian", value: "Armenian" },
  { title: "Australian", value: "Australian" },
  { title: "Austrian", value: "Austrian" },
  { title: "Azerbaijani", value: "Azerbaijani" },
  { title: "Bahamian", value: "Bahamian" },
  { title: "Bahraini", value: "Bahraini" },
  { title: "Bangladeshi", value: "Bangladeshi" },
  { title: "Barbadian", value: "Barbadian" },
  { title: "Barbudans", value: "Barbudans" },
  { title: "Batswana", value: "Batswana" },
  { title: "Belarusian", value: "Belarusian" },
  { title: "Belgian", value: "Belgian" },
  { title: "Belizean", value: "Belizean" },
  { title: "Beninese", value: "Beninese" },
  { title: "Bhutanese", value: "Bhutanese" },
  { title: "Bolivian", value: "Bolivian" },
  { title: "Bosnian", value: "Bosnian" },
  { title: "Brazilian", value: "Brazilian" },
  { title: "British", value: "British" },
  { title: "Bruneian", value: "Bruneian" },
  { title: "Bulgarian", value: "Bulgarian" },
  { title: "Burkinabe", value: "Burkinabe" },
  { title: "Burmese", value: "Burmese" },
  { title: "Burundian", value: "Burundian" },
  { title: "Cambodian", value: "Cambodian" },
  { title: "Cameroonian", value: "Cameroonian" },
  { title: "Canadian", value: "Canadian" },
  { title: "Cape Verdean", value: "Cape Verdean" },
  { title: "Central African", value: "Central African" },
  { title: "Chadian", value: "Chadian" },
  { title: "Chilean", value: "Chilean" },
  { title: "Chinese", value: "Chinese" },
  { title: "Colombian", value: "Colombian" },
  { title: "Comoran", value: "Comoran" },
  { title: "Congolese", value: "Congolese" },
  { title: "Costa Rican", value: "Costa Rican" },
  { title: "Croatian", value: "Croatian" },
  { title: "Cuban", value: "Cuban" },
  { title: "Cypriot", value: "Cypriot" },
  { title: "Czech", value: "Czech" },
  { title: "Danish", value: "Danish" },
  { title: "Djibouti", value: "Djibouti" },
  { title: "Dominican", value: "Dominican" },
  { title: "Dutch", value: "Dutch" },
  { title: "East Timorese", value: "East Timorese" },
  { title: "Ecuadorean", value: "Ecuadorean" },
  { title: "Egyptian", value: "Egyptian" },
  { title: "Emirian", value: "Emirian" },
  { title: "Equatorial Guinean", value: "Equatorial Guinean" },
  { title: "Eritrean", value: "Eritrean" },
  { title: "Estonian", value: "Estonian" },
  { title: "Ethiopian", value: "Ethiopian" },
  { title: "Fijian", value: "Fijian" },
  { title: "Filipino", value: "Filipino" },
  { title: "Finnish", value: "Finnish" },
  { title: "French", value: "French" },
  { title: "Gabonese", value: "Gabonese" },
  { title: "Gambian", value: "Gambian" },
  { title: "Georgian", value: "Georgian" },
  { title: "German", value: "German" },
  { title: "Ghanaian", value: "Ghanaian" },
  { title: "Greek", value: "Greek" },
  { title: "Grenadian", value: "Grenadian" },
  { title: "Guatemalan", value: "Guatemalan" },
  { title: "Guinea-Bissauan", value: "Guinea-Bissauan" },
  { title: "Guinean", value: "Guinean" },
  { title: "Guyanese", value: "Guyanese" },
  { title: "Haitian", value: "Haitian" },
  { title: "Herzegovinian", value: "Herzegovinian" },
  { title: "Honduran", value: "Honduran" },
  { title: "Hungarian", value: "Hungarian" },
  { title: "I-Kiribati", value: "I-Kiribati" },
  { title: "Icelander", value: "Icelander" },
  { title: "Indian", value: "Indian" },
  { title: "Indonesian", value: "Indonesian" },
  { title: "Iranian", value: "Iranian" },
  { title: "Iraqi", value: "Iraqi" },
  { title: "Irish", value: "Irish" },
  { title: "Israeli", value: "Israeli" },
  { title: "Italian", value: "Italian" },
  { title: "Ivorian", value: "Ivorian" },
  { title: "Jamaican", value: "Jamaican" },
  { title: "Japanese", value: "Japanese" },
  { title: "Jordanian", value: "Jordanian" },
  { title: "Kazakhstani", value: "Kazakhstani" },
  { title: "Kenyan", value: "Kenyan" },
  { title: "Kittian and Nevisian", value: "Kittian and Nevisian" },
  { title: "Kuwaiti", value: "Kuwaiti" },
  { title: "Kyrgyz", value: "Kyrgyz" },
  { title: "Laotian", value: "Laotian" },
  { title: "Latvian", value: "Latvian" },
  { title: "Lebanese", value: "Lebanese" },
  { title: "Liberian", value: "Liberian" },
  { title: "Libyan", value: "Libyan" },
  { title: "Liechtensteiner", value: "Liechtensteiner" },
  { title: "Lithuanian", value: "Lithuanian" },
  { title: "Luxembourger", value: "Luxembourger" },
  { title: "Macedonian", value: "Macedonian" },
  { title: "Malagasy", value: "Malagasy" },
  { title: "Malawian", value: "Malawian" },
  { title: "Malaysian", value: "Malaysian" },
  { title: "Maldivan", value: "Maldivan" },
  { title: "Malian", value: "Malian" },
  { title: "Maltese", value: "Maltese" },
  { title: "Marshallese", value: "Marshallese" },
  { title: "Mauritanian", value: "Mauritanian" },
  { title: "Mauritian", value: "Mauritian" },
  { title: "Mexican", value: "Mexican" },
  { title: "Micronesian", value: "Micronesian" },
  { title: "Moldovan", value: "Moldovan" },
  { title: "Monacan", value: "Monacan" },
  { title: "Mongolian", value: "Mongolian" },
  { title: "Moroccan", value: "Moroccan" },
  { title: "Mosotho", value: "Mosotho" },
  { title: "Motswana", value: "Motswana" },
  { title: "Mozambican", value: "Mozambican" },
  { title: "Namibian", value: "Namibian" },
  { title: "Nauruan", value: "Nauruan" },
  { title: "Nepalese", value: "Nepalese" },
  { title: "Netherlander", value: "Netherlander" },
  { title: "New Zealander", value: "New Zealander" },
  { title: "Nicaraguan", value: "Nicaraguan" },
  { title: "Nigerian", value: "Nigerian" },
  { title: "Nigerien", value: "Nigerien" },
  { title: "North Korean", value: "North Korean" },
  { title: "Northern Irish", value: "Northern Irish" },
  { title: "Norwegian", value: "Norwegian" },
  { title: "Omani", value: "Omani" },
  { title: "Pakistani", value: "Pakistani" },
  { title: "Palauan", value: "Palauan" },
  { title: "Panamanian", value: "Panamanian" },
  { title: "Papua New Guinean", value: "Papua New Guinean" },
  { title: "Paraguayan", value: "Paraguayan" },
  { title: "Peruvian", value: "Peruvian" },
  { title: "Polish", value: "Polish" },
  { title: "Portuguese", value: "Portuguese" },
  { title: "Qatari", value: "Qatari" },
  { title: "Romanian", value: "Romanian" },
  { title: "Russian", value: "Russian" },
  { title: "Rwandan", value: "Rwandan" },
  { title: "Saint Lucian", value: "Saint Lucian" },
  { title: "Salvadoran", value: "Salvadoran" },
  { title: "Samoan", value: "Samoan" },
  { title: "San Marinese", value: "San Marinese" },
  { title: "Sao Tomean", value: "Sao Tomean" },
  { title: "Saudi", value: "Saudi" },
  { title: "Scottish", value: "Scottish" },
  { title: "Senegalese", value: "Senegalese" },
  { title: "Serbian", value: "Serbian" },
  { title: "Seychellois", value: "Seychellois" },
  { title: "Sierra Leonean", value: "Sierra Leonean" },
  { title: "Singaporean", value: "Singaporean" },
  { title: "Slovakian", value: "Slovakian" },
  { title: "Slovenian", value: "Slovenian" },
  { title: "Solomon Islander", value: "Solomon Islander" },
  { title: "Somali", value: "Somali" },
  { title: "South African", value: "South African" },
  { title: "South Korean", value: "South Korean" },
  { title: "Spanish", value: "Spanish" },
  { title: "Sri Lankan", value: "Sri Lankan" },
  { title: "Sudanese", value: "Sudanese" },
  { title: "Surinamer", value: "Surinamer" },
  { title: "Swazi", value: "Swazi" },
  { title: "Swedish", value: "Swedish" },
  { title: "Swiss", value: "Swiss" },
  { title: "Syrian", value: "Syrian" },
  { title: "Taiwanese", value: "Taiwanese" },
  { title: "Tajik", value: "Tajik" },
  { title: "Tanzanian", value: "Tanzanian" },
  { title: "Thai", value: "Thai" },
  { title: "Togolese", value: "Togolese" },
  { title: "Tongan", value: "Tongan" },
  { title: "Trinidadian or Tobagonian", value: "Trinidadian or Tobagonian" },
  { title: "Tunisian", value: "Tunisian" },
  { title: "Turkish", value: "Turkish" },
  { title: "Tuvaluan", value: "Tuvaluan" },
  { title: "Ugandan", value: "Ugandan" },
  { title: "Ukrainian", value: "Ukrainian" },
  { title: "Uruguayan", value: "Uruguayan" },
  { title: "Uzbekistani", value: "Uzbekistani" },
  { title: "Venezuelan", value: "Venezuelan" },
  { title: "Vietnamese", value: "Vietnamese" },
  { title: "Welsh", value: "Welsh" },
  { title: "Yemenite", value: "Yemenite" },
  { title: "Zambian", value: "Zambian" },
  { title: "Zimbabwean", value: "Zimbabwean" },
];
